// frontend/src/app/layout/public-layout/header/header.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { TranslocoModule } from '@ngneat/transloco';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { AuthService } from '@core/services/auth.service';
import { LanguageSelectorComponent } from '@shared/components/language-selector/language-selector.component';

@Component({
  selector: 'app-header',
  standalone: true,
  imports: [
    CommonModule,
    RouterLink,
    RouterLinkActive,
    TranslocoModule,
    MatToolbarModule,
    MatButtonModule,
    MatIconModule,
    MatMenuModule,
    LanguageSelectorComponent
  ],
  template: `
    <header class="bg-primary-navy shadow-lg sticky top-0 z-50">
      <nav class="container mx-auto px-4">
        <div class="flex items-center justify-between h-20">
          <!-- Logo -->
          <a routerLink="/" class="flex items-center space-x-2">
            <span class="text-primary-gold text-2xl font-heading font-bold">Empty Legs</span>
            <span class="text-primary-white text-2xl font-heading">Luxury</span>
          </a>

          <!-- Desktop Navigation -->
          <div class="hidden md:flex items-center space-x-8">
            <a routerLink="/" routerLinkActive="text-primary-gold" [routerLinkActiveOptions]="{exact: true}"
               class="text-primary-white hover:text-primary-gold transition-colors">
              {{ 'navigation.home' | transloco }}
            </a>
            <a routerLink="/flights" routerLinkActive="text-primary-gold"
               class="text-primary-white hover:text-primary-gold transition-colors">
              {{ 'navigation.flights' | transloco }}
            </a>
            <a routerLink="/about" routerLinkActive="text-primary-gold"
               class="text-primary-white hover:text-primary-gold transition-colors">
              {{ 'navigation.about' | transloco }}
            </a>
            <a routerLink="/contact" routerLinkActive="text-primary-gold"
               class="text-primary-white hover:text-primary-gold transition-colors">
              {{ 'navigation.contact' | transloco }}
            </a>
          </div>

          <!-- Right Section -->
          <div class="flex items-center space-x-4">
            <app-language-selector></app-language-selector>
            
            @if (authService.isAuthenticated()) {
              <button mat-button [matMenuTriggerFor]="userMenu" class="text-primary-white">
                <mat-icon>account_circle</mat-icon>
                <span class="ml-2 hidden md:inline">{{ currentUser?.firstName }}</span>
              </button>
              <mat-menu #userMenu="matMenu">
                <a mat-menu-item [routerLink]="getDashboardLink()">
                  <mat-icon>dashboard</mat-icon>
                  <span>{{ 'navigation.dashboard' | transloco }}</span>
                </a>
                <a mat-menu-item routerLink="/profile">
                  <mat-icon>person</mat-icon>
                  <span>{{ 'navigation.profile' | transloco }}</span>
                </a>
                <mat-divider></mat-divider>
                <button mat-menu-item (click)="logout()">
                  <mat-icon>logout</mat-icon>
                  <span>{{ 'navigation.logout' | transloco }}</span>
                </button>
              </mat-menu>
            } @else {
              <a routerLink="/auth/login" mat-button class="text-primary-white">
                {{ 'navigation.login' | transloco }}
              </a>
              <a routerLink="/auth/register" mat-raised-button class="btn-premium">
                {{ 'navigation.register' | transloco }}
              </a>
            }

            <!-- Mobile Menu Button -->
            <button mat-icon-button (click)="toggleMobileMenu()" class="md:hidden text-primary-white">
              <mat-icon>{{ mobileMenuOpen ? 'close' : 'menu' }}</mat-icon>
            </button>
          </div>
        </div>

        <!-- Mobile Navigation -->
        @if (mobileMenuOpen) {
          <div class="md:hidden py-4 border-t border-gray-700">
            <div class="flex flex-col space-y-2">
              <a routerLink="/" routerLinkActive="text-primary-gold" [routerLinkActiveOptions]="{exact: true}"
                 class="text-primary-white hover:text-primary-gold transition-colors py-2"
                 (click)="closeMobileMenu()">
                {{ 'navigation.home' | transloco }}
              </a>
              <a routerLink="/flights" routerLinkActive="text-primary-gold"
                 class="text-primary-white hover:text-primary-gold transition-colors py-2"
                 (click)="closeMobileMenu()">
                {{ 'navigation.flights' | transloco }}
              </a>
              <a routerLink="/about" routerLinkActive="text-primary-gold"
                 class="text-primary-white hover:text-primary-gold transition-colors py-2"
                 (click)="closeMobileMenu()">
                {{ 'navigation.about' | transloco }}
              </a>
              <a routerLink="/contact" routerLinkActive="text-primary-gold"
                 class="text-primary-white hover:text-primary-gold transition-colors py-2"
                 (click)="closeMobileMenu()">
                {{ 'navigation.contact' | transloco }}
              </a>
            </div>
          </div>
        }
      </nav>
    </header>
  `,
  styles: []
})
export class HeaderComponent {
  authService = inject(AuthService);
  mobileMenuOpen = false;

  get currentUser() {
    return this.authService.getCurrentUser();
  }

  toggleMobileMenu(): void {
    this.mobileMenuOpen = !this.mobileMenuOpen;
  }

  closeMobileMenu(): void {
    this.mobileMenuOpen = false;
  }

  getDashboardLink(): string {
    const user = this.currentUser;
    if (!user) return '/';
    
    switch (user.role) {
      case 'Admin':
        return '/admin/dashboard';
      case 'Company':
        return '/company/dashboard';
      case 'Customer':
        return '/customer/dashboard';
      default:
        return '/';
    }
  }

  logout(): void {
    this.authService.logout();
  }
}

// frontend/src/components/layout/Header.tsx
'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Plane, Menu, X, User } from 'lucide-react'

export function Header() {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)

  return (
    <header className="fixed top-0 left-0 right-0 z-50 bg-white/95 backdrop-blur-sm border-b border-gray-200">
      <div className="container">
        <div className="flex items-center justify-between h-16">
          {/* Logo */}
          <Link href="/" className="flex items-center space-x-2">
            <div className="flex items-center justify-center w-8 h-8 bg-primary rounded-lg">
              <Plane className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold text-gray-900">Empty Legs</span>
          </Link>

          {/* Desktop Navigation */}
          <nav className="hidden md:flex items-center space-x-8">
            <Link 
              href="/search" 
              className="text-gray-700 hover:text-primary transition-colors"
            >
              Rechercher
            </Link>
            <Link 
              href="/how-it-works" 
              className="text-gray-700 hover:text-primary transition-colors"
            >
              Comment ça marche
            </Link>
            <Link 
              href="/about" 
              className="text-gray-700 hover:text-primary transition-colors"
            >
              À propos
            </Link>
            <Link 
              href="/help" 
              className="text-gray-700 hover:text-primary transition-colors"
            >
              Aide
            </Link>
          </nav>

          {/* Desktop Auth Buttons */}
          <div className="hidden md:flex items-center space-x-4">
            <Link 
              href="/company/login"
              className="text-gray-700 hover:text-primary transition-colors"
            >
              Espace Compagnie
            </Link>
            <Link 
              href="/login"
              className="btn btn-outline btn-sm"
            >
              Connexion
            </Link>
            <Link 
              href="/register"
              className="btn btn-primary btn-sm"
            >
              Inscription
            </Link>
          </div>

          {/* Mobile menu button */}
          <button
            className="md:hidden p-2"
            onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)}
            aria-label="Toggle menu"
          >
            {isMobileMenuOpen ? (
              <X className="w-6 h-6" />
            ) : (
              <Menu className="w-6 h-6" />
            )}
          </button>
        </div>

        {/* Mobile Navigation */}
        {isMobileMenuOpen && (
          <div className="md:hidden">
            <div className="px-2 pt-2 pb-3 space-y-1 bg-white border-t border-gray-200">
              <Link 
                href="/search"
                className="block px-3 py-2 text-gray-700 hover:text-primary transition-colors"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                Rechercher
              </Link>
              <Link 
                href="/how-it-works"
                className="block px-3 py-2 text-gray-700 hover:text-primary transition-colors"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                Comment ça marche
              </Link>
              <Link 
                href="/about"
                className="block px-3 py-2 text-gray-700 hover:text-primary transition-colors"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                À propos
              </Link>
              <Link 
                href="/help"
                className="block px-3 py-2 text-gray-700 hover:text-primary transition-colors"
                onClick={() => setIsMobileMenuOpen(false)}
              >
                Aide
              </Link>
              <div className="pt-4 pb-3 border-t border-gray-200">
                <Link 
                  href="/company/login"
                  className="block px-3 py-2 text-gray-700 hover:text-primary transition-colors"
                  onClick={() => setIsMobileMenuOpen(false)}
                >
                  Espace Compagnie
                </Link>
                <div className="flex space-x-2 px-3 pt-2">
                  <Link 
                    href="/login"
                    className="btn btn-outline btn-sm flex-1"
                    onClick={() => setIsMobileMenuOpen(false)}
                  >
                    Connexion
                  </Link>
                  <Link 
                    href="/register"
                    className="btn btn-primary btn-sm flex-1"
                    onClick={() => setIsMobileMenuOpen(false)}
                  >
                    Inscription
                  </Link>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </header>
  )
}
